### ISSUE TITLE
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory...

### ISSUE THREAD

**Issue by patkujawa-wf** [rchakra3/zsh_history#1]
Thank you for this, it looks like exactly what I want. However, trying to run it, I got an exception right off the bat. Is it obvious what the problem is? I might try to fix it myself but am not yet familiar with the code.

```
[patkujawa@LS2-00159 Mon Dec 10 10:56:41 MST 2018] ~/oss/zsh_history (master)
❯ python2 ./src/hist.py -b                                                                                                                                                      ⏎
Traceback (most recent call last):
  File "./src/hist.py", line 121, in <module>
    backup(args.path, args.dbname)
  File "./src/hist.py", line 59, in backup
    u" VALUES(?,?,?)", rows)
sqlite3.ProgrammingError: You must not use 8-bit bytestrings unless you use a text_factory that can interpret 8-bit bytestrings (like text_factory = str). It is highly recommended that you instead just switch your application to Unicode strings.
```

**Comment by rohancme** [comment]
This might be because I'm using Python3 and it looks like you're using 2.
Can you try 3 to see if that fixes it?

I'll try and take a look tonight if that's not it!

**Comment by patkujawa-wf** [comment]
Oh, sorry, I tried both but figured it was v2-only because of syntax error:
```
[patkujawa@LS2-00159 Mon Dec 10 10:56:54 MST 2018] ~/oss/zsh_history (master)
❯ python3 ./src/hist.py -b                                                                                                                                                      ⏎
  File "./src/hist.py", line 27
    print "table created successfully"
                                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("table created successfully")?
```

**Comment by rohancme** [comment]
@patkujawa-wf do you mind trying again? Seems I had some local changes that I hadn't pushed up.

Thanks for opening the issue! :)

**Comment by patkujawa-wf** [comment]
Success! Thank you!
